spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27018/librarydb
      database: librarydb

server:
  port: 8080
